
SET(USE_CUDA_VERSION "9.0" CACHE STRING "Expected CUDA version")

SET_PROPERTY(CACHE USE_CUDA_VERSION PROPERTY STRINGS 9.0)


IF(USE_CUDA_VERSION EQUAL 9.0)
	FIND_PATH(CUDA_INCLUDE_DIR NAMES cuda.h HINTS C:/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v9.0/include)
	FIND_LIBRARY(CUDA_LIB_DIR NAMES cudart HINTS C:/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v9.0/lib/x64)
ENDIF()

IF(USE_CUDA_VERSION EQUAL 9.0)
  SET(CUDA_LIBRARIES
    cudart_static)

  SET(CUDA_INCLUDE_DIRS ${CUDA_INCLUDE_DIR})
ENDIF()
